# Site
#repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Elliot Pack
email: epack1017@gmail.com
website: 

# Social links
#twitter_username: facespics
github_username:  e-pack
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: https://www.linkedin.com/in/unavailable/
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.PNG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Elliot and I'm a data analyst from Washington, D.C. I currently work with Baker Tilly's Government Contracting Consulting Services (GCAS) team to identify, quantify, and manage government contract risk through regulatory and compliance consulting.  

  My background is in finance and accounting but I am also skilled in: <mark>SQL</mark> and <mark>Tableau</mark> and <mark>Python</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in data science some of my other interests and hobbies are:
   - Running
   - Photography
   - Cooking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
