# Site
#repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Elliot Pack
email: epack1017@gmail.com
website: 

# Social links
#twitter_username: facespics
github_username:  e-pack
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: elliot-pack-4478368
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/me.PNG
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Elliot and I'm pursuing a position as a data analyst. I studied finance and accounting at the University of Maryland and am currently a consultant at Baker Tilly. 

  I am most skilled in: <mark>SQL</mark> and <mark>Tableau</mark> and <mark>Excel</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
